In [21]:
import numpy as np 
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tik = time.time()
v = np.dot(a,b)
tok = time.time()
print(v,"--",1000*(tok-tik),"ms")

250488.8530290324 -- 0.9963512420654297 ms


In [22]:
v = 0
tik = time.time()
for i in range(1000000):
    v+=a[i]*b[i]
tok = time.time()
print(v,"--",1000*(tok-tik),"ms")

250488.8530290228 -- 622.3809719085693 ms


In [23]:
# 广播
A = np.array([[56.0,0,4.4,68.0],
             [1.2,104,52,8],
             [1.8,135,99,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [24]:
col = A.sum(axis=0)
# axis = 0:列, axis = 1:行
print(col)

[ 59.  239.  155.4  76.9]


In [25]:
percentage = 100*A/col.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [26]:
# 秩为1的数组
array_a = np.random.randn(5)
# 5*1的向量
vector_a = np.random.randn(5,1)
# 1*5的向量
vector_b = np.random.randn(1,5)
# 3*3的向量
vector_c = np.random.randn(3,3)

print(array_a)
print(vector_a)
print(vector_b)
print(vector_c)
print(array_a.reshape((5,1)))

[-0.73455047 -0.03382991  0.161577   -0.08907235 -0.4922561 ]
[[ 0.97080125]
 [ 0.11246483]
 [-0.51621821]
 [-1.62152641]
 [-0.23573427]]
[[ 1.1599227  -1.5184993   0.25954146 -2.02668332 -0.26095551]]
[[-0.9660722   0.76428046  0.07247342]
 [-1.19058997 -3.34152293 -0.38616951]
 [-0.33405513 -0.25050605 -0.59999108]]
[[-0.73455047]
 [-0.03382991]
 [ 0.161577  ]
 [-0.08907235]
 [-0.4922561 ]]


In [28]:
# assert(array_a.shape == (5,1)) # wrong
assert(vector_a.shape == (5,1))